/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Api;
// uncomment below to import models
//using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Test.Api
{
    /// <summary>
    ///  Class for testing SousTacheApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SousTacheApiTests : IDisposable
    {
        private SousTacheApi instance;

        public SousTacheApiTests()
        {
            instance = new SousTacheApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SousTacheApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SousTacheApi
            //Assert.IsType<SousTacheApi>(instance);
        }

        /// <summary>
        /// Test SoustacheAjouterPost
        /// </summary>
        [Fact]
        public void SoustacheAjouterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SousTacheCore sousTacheCore = null;
            //var response = instance.SoustacheAjouterPost(sousTacheCore);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test SoustacheListeGet
        /// </summary>
        [Fact]
        public void SoustacheListeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SoustacheListeGet();
            //Assert.IsType<List<SousTacheCore>>(response);
        }

        /// <summary>
        /// Test SoustacheListeParConditionParPagePageNumeroPageTaillePost
        /// </summary>
        [Fact]
        public void SoustacheListeParConditionParPagePageNumeroPageTaillePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageNumero = null;
            //int pageTaille = null;
            //CritereRecherche critereRecherche = null;
            //var response = instance.SoustacheListeParConditionParPagePageNumeroPageTaillePost(pageNumero, pageTaille, critereRecherche);
            //Assert.IsType<SousTacheCoreResultatPage>(response);
        }

        /// <summary>
        /// Test SoustacheListeParConditionPost
        /// </summary>
        [Fact]
        public void SoustacheListeParConditionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CritereRecherche critereRecherche = null;
            //var response = instance.SoustacheListeParConditionPost(critereRecherche);
            //Assert.IsType<List<SousTacheCore>>(response);
        }

        /// <summary>
        /// Test SoustacheListeParPagePageNumeroPageTailleGet
        /// </summary>
        [Fact]
        public void SoustacheListeParPagePageNumeroPageTailleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageNumero = null;
            //int pageTaille = null;
            //var response = instance.SoustacheListeParPagePageNumeroPageTailleGet(pageNumero, pageTaille);
            //Assert.IsType<SousTacheCoreResultatPage>(response);
        }

        /// <summary>
        /// Test SoustacheModifierPut
        /// </summary>
        [Fact]
        public void SoustacheModifierPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SousTacheCore sousTacheCore = null;
            //var response = instance.SoustacheModifierPut(sousTacheCore);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test SoustacheObtenirIdIdGet
        /// </summary>
        [Fact]
        public void SoustacheObtenirIdIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.SoustacheObtenirIdIdGet(id);
            //Assert.IsType<SousTacheCore>(response);
        }

        /// <summary>
        /// Test SoustacheSupprimerIdIdDelete
        /// </summary>
        [Fact]
        public void SoustacheSupprimerIdIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.SoustacheSupprimerIdIdDelete(id);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test SoustacheSupprimerParConditionPost
        /// </summary>
        [Fact]
        public void SoustacheSupprimerParConditionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CritereRecherche critereRecherche = null;
            //var response = instance.SoustacheSupprimerParConditionPost(critereRecherche);
            //Assert.IsType<bool>(response);
        }
    }
}
