/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Api;
// uncomment below to import models
//using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TacheApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TacheApiTests : IDisposable
    {
        private TacheApi instance;

        public TacheApiTests()
        {
            instance = new TacheApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TacheApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TacheApi
            //Assert.IsType<TacheApi>(instance);
        }

        /// <summary>
        /// Test ApiTachesAjouterPost
        /// </summary>
        [Fact]
        public void ApiTachesAjouterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TacheCore tacheCore = null;
            //var response = instance.ApiTachesAjouterPost(tacheCore);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test ApiTachesGet
        /// </summary>
        [Fact]
        public void ApiTachesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //var response = instance.ApiTachesGet(page, pageSize);
            //Assert.IsType<TacheCoreResultatPage>(response);
        }

        /// <summary>
        /// Test ApiTachesListeGet
        /// </summary>
        [Fact]
        public void ApiTachesListeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiTachesListeGet();
            //Assert.IsType<List<TacheCore>>(response);
        }

        /// <summary>
        /// Test ApiTachesListeParConditionParPagePageNumeroPageTaillePost
        /// </summary>
        [Fact]
        public void ApiTachesListeParConditionParPagePageNumeroPageTaillePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageNumero = null;
            //int pageTaille = null;
            //CritereRecherche critereRecherche = null;
            //var response = instance.ApiTachesListeParConditionParPagePageNumeroPageTaillePost(pageNumero, pageTaille, critereRecherche);
            //Assert.IsType<TacheCoreResultatPage>(response);
        }

        /// <summary>
        /// Test ApiTachesListeParConditionPost
        /// </summary>
        [Fact]
        public void ApiTachesListeParConditionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CritereRecherche critereRecherche = null;
            //var response = instance.ApiTachesListeParConditionPost(critereRecherche);
            //Assert.IsType<List<TacheCore>>(response);
        }

        /// <summary>
        /// Test ApiTachesListeParPagePageNumeroPageTailleGet
        /// </summary>
        [Fact]
        public void ApiTachesListeParPagePageNumeroPageTailleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageNumero = null;
            //int pageTaille = null;
            //var response = instance.ApiTachesListeParPagePageNumeroPageTailleGet(pageNumero, pageTaille);
            //Assert.IsType<TacheCoreResultatPage>(response);
        }

        /// <summary>
        /// Test ApiTachesModifierPut
        /// </summary>
        [Fact]
        public void ApiTachesModifierPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TacheCore tacheCore = null;
            //var response = instance.ApiTachesModifierPut(tacheCore);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test ApiTachesObtenirIdIdGet
        /// </summary>
        [Fact]
        public void ApiTachesObtenirIdIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ApiTachesObtenirIdIdGet(id);
            //Assert.IsType<TacheCore>(response);
        }

        /// <summary>
        /// Test ApiTachesSupprimerIdIdDelete
        /// </summary>
        [Fact]
        public void ApiTachesSupprimerIdIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ApiTachesSupprimerIdIdDelete(id);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test ApiTachesSupprimerParConditionPost
        /// </summary>
        [Fact]
        public void ApiTachesSupprimerParConditionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CritereRecherche critereRecherche = null;
            //var response = instance.ApiTachesSupprimerParConditionPost(critereRecherche);
            //Assert.IsType<bool>(response);
        }
    }
}
