/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Api;
// uncomment below to import models
//using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TypeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TypeApiTests : IDisposable
    {
        private TypeApi instance;

        public TypeApiTests()
        {
            instance = new TypeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TypeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TypeApi
            //Assert.IsType<TypeApi>(instance);
        }

        /// <summary>
        /// Test TypeAjouterPost
        /// </summary>
        [Fact]
        public void TypeAjouterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TypeCore typeCore = null;
            //var response = instance.TypeAjouterPost(typeCore);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test TypeListeGet
        /// </summary>
        [Fact]
        public void TypeListeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TypeListeGet();
            //Assert.IsType<List<TypeCore>>(response);
        }

        /// <summary>
        /// Test TypeListeParConditionParPagePageNumeroPageTaillePost
        /// </summary>
        [Fact]
        public void TypeListeParConditionParPagePageNumeroPageTaillePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageNumero = null;
            //int pageTaille = null;
            //CritereRecherche critereRecherche = null;
            //var response = instance.TypeListeParConditionParPagePageNumeroPageTaillePost(pageNumero, pageTaille, critereRecherche);
            //Assert.IsType<TypeCoreResultatPage>(response);
        }

        /// <summary>
        /// Test TypeListeParConditionPost
        /// </summary>
        [Fact]
        public void TypeListeParConditionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CritereRecherche critereRecherche = null;
            //var response = instance.TypeListeParConditionPost(critereRecherche);
            //Assert.IsType<List<TypeCore>>(response);
        }

        /// <summary>
        /// Test TypeListeParPagePageNumeroPageTailleGet
        /// </summary>
        [Fact]
        public void TypeListeParPagePageNumeroPageTailleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int pageNumero = null;
            //int pageTaille = null;
            //var response = instance.TypeListeParPagePageNumeroPageTailleGet(pageNumero, pageTaille);
            //Assert.IsType<TypeCoreResultatPage>(response);
        }

        /// <summary>
        /// Test TypeModifierPut
        /// </summary>
        [Fact]
        public void TypeModifierPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TypeCore typeCore = null;
            //var response = instance.TypeModifierPut(typeCore);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test TypeObtenirIdIdGet
        /// </summary>
        [Fact]
        public void TypeObtenirIdIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.TypeObtenirIdIdGet(id);
            //Assert.IsType<TypeCore>(response);
        }

        /// <summary>
        /// Test TypeSupprimerIdIdDelete
        /// </summary>
        [Fact]
        public void TypeSupprimerIdIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.TypeSupprimerIdIdDelete(id);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test TypeSupprimerParConditionPost
        /// </summary>
        [Fact]
        public void TypeSupprimerParConditionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CritereRecherche critereRecherche = null;
            //var response = instance.TypeSupprimerParConditionPost(critereRecherche);
            //Assert.IsType<bool>(response);
        }
    }
}
