/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gestprojet.Core.ApiParamSociete.Client.Api;
using Gestprojet.Core.ApiParamSociete.Client.Model;
using Gestprojet.Core.ApiParamSociete.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gestprojet.Core.ApiParamSociete.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AttachementCoreResultatPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachementCoreResultatPageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttachementCoreResultatPage
        //private AttachementCoreResultatPage instance;

        public AttachementCoreResultatPageTests()
        {
            // TODO uncomment below to create an instance of AttachementCoreResultatPage
            //instance = new AttachementCoreResultatPage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttachementCoreResultatPage
        /// </summary>
        [Fact]
        public void AttachementCoreResultatPageInstanceTest()
        {
            // TODO uncomment below to test "IsType" AttachementCoreResultatPage
            //Assert.IsType<AttachementCoreResultatPage>(instance);
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }
        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

    }

}
