/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gestprojet.Core.ApiParamSociete.Client.Api;
using Gestprojet.Core.ApiParamSociete.Client.Model;
using Gestprojet.Core.ApiParamSociete.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gestprojet.Core.ApiParamSociete.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PermissionCore
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PermissionCoreTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PermissionCore
        //private PermissionCore instance;

        public PermissionCoreTests()
        {
            // TODO uncomment below to create an instance of PermissionCore
            //instance = new PermissionCore();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PermissionCore
        /// </summary>
        [Fact]
        public void PermissionCoreInstanceTest()
        {
            // TODO uncomment below to test "IsType" PermissionCore
            //Assert.IsType<PermissionCore>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Fact]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }
        /// <summary>
        /// Test the property 'ModuleId'
        /// </summary>
        [Fact]
        public void ModuleIdTest()
        {
            // TODO unit test for the property 'ModuleId'
        }
        /// <summary>
        /// Test the property 'PeutLire'
        /// </summary>
        [Fact]
        public void PeutLireTest()
        {
            // TODO unit test for the property 'PeutLire'
        }
        /// <summary>
        /// Test the property 'PeutCreer'
        /// </summary>
        [Fact]
        public void PeutCreerTest()
        {
            // TODO unit test for the property 'PeutCreer'
        }
        /// <summary>
        /// Test the property 'PeutModifier'
        /// </summary>
        [Fact]
        public void PeutModifierTest()
        {
            // TODO unit test for the property 'PeutModifier'
        }
        /// <summary>
        /// Test the property 'PeutSupprimer'
        /// </summary>
        [Fact]
        public void PeutSupprimerTest()
        {
            // TODO unit test for the property 'PeutSupprimer'
        }
        /// <summary>
        /// Test the property 'Actif'
        /// </summary>
        [Fact]
        public void ActifTest()
        {
            // TODO unit test for the property 'Actif'
        }

    }

}
