/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITacheApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>bool</returns>
        bool ApiTachesAjouterPost(TacheCore tacheCore = default(TacheCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiTachesAjouterPostWithHttpInfo(TacheCore tacheCore = default(TacheCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>TacheCoreResultatPage</returns>
        TacheCoreResultatPage ApiTachesGet(int? page = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>ApiResponse of TacheCoreResultatPage</returns>
        ApiResponse<TacheCoreResultatPage> ApiTachesGetWithHttpInfo(int? page = default(int?), int? pageSize = default(int?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;TacheCore&gt;</returns>
        List<TacheCore> ApiTachesListeGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;TacheCore&gt;</returns>
        ApiResponse<List<TacheCore>> ApiTachesListeGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>TacheCoreResultatPage</returns>
        TacheCoreResultatPage ApiTachesListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of TacheCoreResultatPage</returns>
        ApiResponse<TacheCoreResultatPage> ApiTachesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;TacheCore&gt;</returns>
        List<TacheCore> ApiTachesListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;TacheCore&gt;</returns>
        ApiResponse<List<TacheCore>> ApiTachesListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>TacheCoreResultatPage</returns>
        TacheCoreResultatPage ApiTachesListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of TacheCoreResultatPage</returns>
        ApiResponse<TacheCoreResultatPage> ApiTachesListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>bool</returns>
        bool ApiTachesModifierPut(TacheCore tacheCore = default(TacheCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiTachesModifierPutWithHttpInfo(TacheCore tacheCore = default(TacheCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>TacheCore</returns>
        TacheCore ApiTachesObtenirIdIdGet(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of TacheCore</returns>
        ApiResponse<TacheCore> ApiTachesObtenirIdIdGetWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        bool ApiTachesSupprimerIdIdDelete(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiTachesSupprimerIdIdDeleteWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        bool ApiTachesSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiTachesSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITacheApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiTachesAjouterPostAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiTachesAjouterPostWithHttpInfoAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCoreResultatPage</returns>
        System.Threading.Tasks.Task<TacheCoreResultatPage> ApiTachesGetAsync(int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<TacheCoreResultatPage>> ApiTachesGetWithHttpInfoAsync(int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;TacheCore&gt;</returns>
        System.Threading.Tasks.Task<List<TacheCore>> ApiTachesListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;TacheCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TacheCore>>> ApiTachesListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCoreResultatPage</returns>
        System.Threading.Tasks.Task<TacheCoreResultatPage> ApiTachesListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<TacheCoreResultatPage>> ApiTachesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;TacheCore&gt;</returns>
        System.Threading.Tasks.Task<List<TacheCore>> ApiTachesListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;TacheCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TacheCore>>> ApiTachesListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCoreResultatPage</returns>
        System.Threading.Tasks.Task<TacheCoreResultatPage> ApiTachesListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<TacheCoreResultatPage>> ApiTachesListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiTachesModifierPutAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiTachesModifierPutWithHttpInfoAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCore</returns>
        System.Threading.Tasks.Task<TacheCore> ApiTachesObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCore)</returns>
        System.Threading.Tasks.Task<ApiResponse<TacheCore>> ApiTachesObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiTachesSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiTachesSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiTachesSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiTachesSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITacheApi : ITacheApiSync, ITacheApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TacheApi : ITacheApi
    {
        private Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TacheApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TacheApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TacheApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TacheApi(String basePath)
        {
            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                new Gestprojet.Core.ApiParamSociete.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TacheApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TacheApi(Gestprojet.Core.ApiParamSociete.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TacheApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TacheApi(Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient client, Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient asyncClient, Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool ApiTachesAjouterPost(TacheCore tacheCore = default(TacheCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiTachesAjouterPostWithHttpInfo(tacheCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiTachesAjouterPostWithHttpInfo(TacheCore tacheCore = default(TacheCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = tacheCore;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/api/taches/ajouter", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiTachesAjouterPostAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiTachesAjouterPostWithHttpInfoAsync(tacheCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiTachesAjouterPostWithHttpInfoAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = tacheCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/api/taches/ajouter", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>TacheCoreResultatPage</returns>
        public TacheCoreResultatPage ApiTachesGet(int? page = default(int?), int? pageSize = default(int?))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> localVarResponse = ApiTachesGetWithHttpInfo(page, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>ApiResponse of TacheCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> ApiTachesGetWithHttpInfo(int? page = default(int?), int? pageSize = default(int?))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<TacheCoreResultatPage>("/api/taches", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<TacheCoreResultatPage> ApiTachesGetAsync(int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> localVarResponse = await ApiTachesGetWithHttpInfoAsync(page, pageSize, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage>> ApiTachesGetWithHttpInfoAsync(int? page = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TacheCoreResultatPage>("/api/taches", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;TacheCore&gt;</returns>
        public List<TacheCore> ApiTachesListeGet()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>> localVarResponse = ApiTachesListeGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;TacheCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>> ApiTachesListeGetWithHttpInfo()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<TacheCore>>("/api/taches/liste", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;TacheCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<TacheCore>> ApiTachesListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>> localVarResponse = await ApiTachesListeGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;TacheCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>>> ApiTachesListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<TacheCore>>("/api/taches/liste", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>TacheCoreResultatPage</returns>
        public TacheCoreResultatPage ApiTachesListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> localVarResponse = ApiTachesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(pageNumero, pageTaille, critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of TacheCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> ApiTachesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<TacheCoreResultatPage>("/api/taches/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<TacheCoreResultatPage> ApiTachesListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> localVarResponse = await ApiTachesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(pageNumero, pageTaille, critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage>> ApiTachesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<TacheCoreResultatPage>("/api/taches/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;TacheCore&gt;</returns>
        public List<TacheCore> ApiTachesListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>> localVarResponse = ApiTachesListeParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;TacheCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>> ApiTachesListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<TacheCore>>("/api/taches/liste-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;TacheCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<TacheCore>> ApiTachesListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>> localVarResponse = await ApiTachesListeParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;TacheCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<TacheCore>>> ApiTachesListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<TacheCore>>("/api/taches/liste-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>TacheCoreResultatPage</returns>
        public TacheCoreResultatPage ApiTachesListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> localVarResponse = ApiTachesListeParPagePageNumeroPageTailleGetWithHttpInfo(pageNumero, pageTaille);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of TacheCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> ApiTachesListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<TacheCoreResultatPage>("/api/taches/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<TacheCoreResultatPage> ApiTachesListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage> localVarResponse = await ApiTachesListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(pageNumero, pageTaille, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCoreResultatPage>> ApiTachesListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TacheCoreResultatPage>("/api/taches/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool ApiTachesModifierPut(TacheCore tacheCore = default(TacheCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiTachesModifierPutWithHttpInfo(tacheCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiTachesModifierPutWithHttpInfo(TacheCore tacheCore = default(TacheCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = tacheCore;


            // make the HTTP request
            var localVarResponse = this.Client.Put<bool>("/api/taches/modifier", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiTachesModifierPutAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiTachesModifierPutWithHttpInfoAsync(tacheCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tacheCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiTachesModifierPutWithHttpInfoAsync(TacheCore tacheCore = default(TacheCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = tacheCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<bool>("/api/taches/modifier", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>TacheCore</returns>
        public TacheCore ApiTachesObtenirIdIdGet(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCore> localVarResponse = ApiTachesObtenirIdIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of TacheCore</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCore> ApiTachesObtenirIdIdGetWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling TacheApi->ApiTachesObtenirIdIdGet");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<TacheCore>("/api/taches/obtenir/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TacheCore</returns>
        public async System.Threading.Tasks.Task<TacheCore> ApiTachesObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCore> localVarResponse = await ApiTachesObtenirIdIdGetWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TacheCore)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<TacheCore>> ApiTachesObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling TacheApi->ApiTachesObtenirIdIdGet");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TacheCore>("/api/taches/obtenir/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        public bool ApiTachesSupprimerIdIdDelete(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiTachesSupprimerIdIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiTachesSupprimerIdIdDeleteWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling TacheApi->ApiTachesSupprimerIdIdDelete");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<bool>("/api/taches/supprimer/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiTachesSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiTachesSupprimerIdIdDeleteWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiTachesSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling TacheApi->ApiTachesSupprimerIdIdDelete");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<bool>("/api/taches/supprimer/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        public bool ApiTachesSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiTachesSupprimerParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiTachesSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/api/taches/supprimer-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiTachesSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiTachesSupprimerParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiTachesSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/api/taches/supprimer-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiTachesSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
