using Gestprojet.Core.ApiParamSociete.Client.Model;
using Gestprojet.Metier.ApiParamSociete.Domain.Interfaces.Commun;
using Gestprojet.Metier.ApiParamSociete.Domain.Interfaces.Societe.Business;
using Gestprojet.Metier.ApiParamSociete.Domain.Models.Societe;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gestprojet.Metier.ApiParamSociete.WebApi.Controllers.Societe
{
    [ApiController]
    [Route("api/DemandeSociete")]
    [AllowAnonymous]
    [Microsoft.AspNetCore.Cors.EnableCors("AllowAllWithCredentials")]
    public class DemandeSocieteController : ControllerBase
    {
        private readonly IApplicationBusiness _applicationBusiness;
        private readonly ISocieteBusiness _societeBusiness;
        private readonly IUtilisateurBusiness _utilisateurBusiness;

        public DemandeSocieteController(
            IApplicationBusiness applicationBusiness, 
            ISocieteBusiness societeBusiness,
            IUtilisateurBusiness utilisateurBusiness)
        {
            _applicationBusiness = applicationBusiness;
            _societeBusiness = societeBusiness;
            _utilisateurBusiness = utilisateurBusiness;
        }

        [HttpPost("soumettre")]
        public async Task<IActionResult> Soumettre([FromBody] DemandeSocieteRequest request)
        {
            if (request == null || string.IsNullOrWhiteSpace(request.SocieteNom) || string.IsNullOrWhiteSpace(request.AdminEmail))
                return BadRequest("Données invalides");

            var application = new ApplicationCore
            {
                // Id will be generated by the repository
                Type = "DemandeSociete",
                Titre = request.SocieteNom,
                Description = JsonConvert.SerializeObject(new { 
                    request.AdminNom, 
                    request.AdminEmail, 
                    request.AdminPassword,
                    request.SocieteAdresse,
                    request.Telephone
                }),
                Statut = "En_attente",
                AppelDate = DateTime.Now,
                Actif = true
            };

            var result = await _applicationBusiness.AjouterOuModifierAsync(application);
            return result.Success ? Ok(new { success = true, message = "Demande envoyée avec succès" }) : BadRequest(result.Message);
        }

        [HttpGet("liste")]
        public async Task<IActionResult> GetListe()
        {
            var critere = new ConditionRecherche
            {
                Criteres = new Dictionary<string, string> { { "Type", "DemandeSociete" } }
            };
            var list = await _applicationBusiness.ListeParCritereAsync(critere);
            return Ok(list);
        }

        [HttpPost("traiter")]
        public async Task<IActionResult> Traiter([FromBody] TraitementDemandeRequest request)
        {
            var demande = await _applicationBusiness.ObtenirAsync(request.DemandeId);
            if (demande == null) return NotFound("Demande introuvable");

            if (request.Approuver)
            {
                var details = JsonConvert.DeserializeObject<dynamic>(demande.Description);
                string societeId = "SOC_" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
                string adminId = "USR_" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();

                // 1. Créer la société
                var societe = new SocieteCore
                {
                    Id = societeId,
                    Nom = demande.Titre,
                    Adresse = details.SocieteAdresse ?? "",
                    Actif = true,
                    PlanAbonnement = "Standard"
                };
                var societeResult = await _societeBusiness.AjouterOuModifierAsync(societe);
                if (!societeResult.Success) return StatusCode(500, "Erreur lors de la création de la société : " + societeResult.Message);

                // 2. Créer l'admin
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword((string)details.AdminPassword);
                var admin = new UtilisateurCore
                {
                    Id = adminId,
                    Nom = details.AdminNom,
                    Email = details.AdminEmail,
                    MotDePasse = hashedPassword,
                    TypeUtilisateurId = "T002", // Admin Société
                    SocieteId = societeId,
                    Actif = true
                };
                var adminResult = await _utilisateurBusiness.AjouterOuModifierAsync(admin);
                if (!adminResult.Success) return StatusCode(500, "Erreur lors de la création de l'administrateur : " + adminResult.Message);

                demande.Statut = "Approuvée";
            }
            else
            {
                demande.Statut = "Refusée";
            }

            await _applicationBusiness.AjouterOuModifierAsync(demande);
            return Ok(new { success = true, message = request.Approuver ? "Société créée" : "Demande refusée" });
        }
    }

    public class DemandeSocieteRequest
    {
        [JsonProperty("societeNom")]
        public required string SocieteNom { get; set; }

        [JsonProperty("societeAdresse")]
        public required string SocieteAdresse { get; set; }

        [JsonProperty("adminNom")]
        public required string AdminNom { get; set; }

        [JsonProperty("adminEmail")]
        public required string AdminEmail { get; set; }

        [JsonProperty("adminPassword")]
        public required string AdminPassword { get; set; }

        [JsonProperty("telephone")]
        public required string Telephone { get; set; }
    }

    public class TraitementDemandeRequest
    {
        public required string DemandeId { get; set; }
        public required bool Approuver { get; set; }
    }
}
