-- Execute this script in SQL Server Management Studio
-- to add missing columns to the Application table

USE [GestionProjetDB];
GO

-- Add columns if they don't exist
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'Type')
    ALTER TABLE [Application] ADD [Type] NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'SocieteId')
    ALTER TABLE [Application] ADD [SocieteId] NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'OffreId')
    ALTER TABLE [Application] ADD [OffreId] NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'Titre')
    ALTER TABLE [Application] ADD [Titre] NVARCHAR(255) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'Lieu')
    ALTER TABLE [Application] ADD [Lieu] NVARCHAR(255) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'Salaire')
    ALTER TABLE [Application] ADD [Salaire] NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'Poste')
    ALTER TABLE [Application] ADD [Poste] NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Application' AND COLUMN_NAME = 'Quiz')
    ALTER TABLE [Application] ADD [Quiz] NVARCHAR(100) NULL;

PRINT 'Columns added successfully.';
