/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPermissionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>bool</returns>
        bool PermissionAjouterPost(PermissionCore permissionCore = default(PermissionCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> PermissionAjouterPostWithHttpInfo(PermissionCore permissionCore = default(PermissionCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;PermissionCore&gt;</returns>
        List<PermissionCore> PermissionListeGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;PermissionCore&gt;</returns>
        ApiResponse<List<PermissionCore>> PermissionListeGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>PermissionCoreResultatPage</returns>
        PermissionCoreResultatPage PermissionListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of PermissionCoreResultatPage</returns>
        ApiResponse<PermissionCoreResultatPage> PermissionListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;PermissionCore&gt;</returns>
        List<PermissionCore> PermissionListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;PermissionCore&gt;</returns>
        ApiResponse<List<PermissionCore>> PermissionListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>PermissionCoreResultatPage</returns>
        PermissionCoreResultatPage PermissionListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of PermissionCoreResultatPage</returns>
        ApiResponse<PermissionCoreResultatPage> PermissionListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>bool</returns>
        bool PermissionModifierPut(PermissionCore permissionCore = default(PermissionCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> PermissionModifierPutWithHttpInfo(PermissionCore permissionCore = default(PermissionCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>PermissionCore</returns>
        PermissionCore PermissionObtenirIdIdGet(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of PermissionCore</returns>
        ApiResponse<PermissionCore> PermissionObtenirIdIdGetWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        bool PermissionSupprimerIdIdDelete(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> PermissionSupprimerIdIdDeleteWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        bool PermissionSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> PermissionSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPermissionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> PermissionAjouterPostAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> PermissionAjouterPostWithHttpInfoAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PermissionCore&gt;</returns>
        System.Threading.Tasks.Task<List<PermissionCore>> PermissionListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PermissionCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PermissionCore>>> PermissionListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PermissionCoreResultatPage</returns>
        System.Threading.Tasks.Task<PermissionCoreResultatPage> PermissionListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PermissionCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<PermissionCoreResultatPage>> PermissionListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PermissionCore&gt;</returns>
        System.Threading.Tasks.Task<List<PermissionCore>> PermissionListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PermissionCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PermissionCore>>> PermissionListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PermissionCoreResultatPage</returns>
        System.Threading.Tasks.Task<PermissionCoreResultatPage> PermissionListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PermissionCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<PermissionCoreResultatPage>> PermissionListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> PermissionModifierPutAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> PermissionModifierPutWithHttpInfoAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PermissionCore</returns>
        System.Threading.Tasks.Task<PermissionCore> PermissionObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PermissionCore)</returns>
        System.Threading.Tasks.Task<ApiResponse<PermissionCore>> PermissionObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> PermissionSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> PermissionSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> PermissionSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> PermissionSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPermissionApi : IPermissionApiSync, IPermissionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PermissionApi : IPermissionApi
    {
        private Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PermissionApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PermissionApi(String basePath)
        {
            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                new Gestprojet.Core.ApiParamSociete.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PermissionApi(Gestprojet.Core.ApiParamSociete.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PermissionApi(Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient client, Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient asyncClient, Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool PermissionAjouterPost(PermissionCore permissionCore = default(PermissionCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = PermissionAjouterPostWithHttpInfo(permissionCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> PermissionAjouterPostWithHttpInfo(PermissionCore permissionCore = default(PermissionCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = permissionCore;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/permission/ajouter", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> PermissionAjouterPostAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await PermissionAjouterPostWithHttpInfoAsync(permissionCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> PermissionAjouterPostWithHttpInfoAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = permissionCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/permission/ajouter", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;PermissionCore&gt;</returns>
        public List<PermissionCore> PermissionListeGet()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>> localVarResponse = PermissionListeGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;PermissionCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>> PermissionListeGetWithHttpInfo()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<PermissionCore>>("/permission/liste", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PermissionCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<PermissionCore>> PermissionListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>> localVarResponse = await PermissionListeGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PermissionCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>>> PermissionListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<PermissionCore>>("/permission/liste", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>PermissionCoreResultatPage</returns>
        public PermissionCoreResultatPage PermissionListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage> localVarResponse = PermissionListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(pageNumero, pageTaille, critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of PermissionCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage> PermissionListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PermissionCoreResultatPage>("/permission/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PermissionCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<PermissionCoreResultatPage> PermissionListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage> localVarResponse = await PermissionListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(pageNumero, pageTaille, critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PermissionCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage>> PermissionListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PermissionCoreResultatPage>("/permission/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;PermissionCore&gt;</returns>
        public List<PermissionCore> PermissionListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>> localVarResponse = PermissionListeParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;PermissionCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>> PermissionListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<PermissionCore>>("/permission/liste-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PermissionCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<PermissionCore>> PermissionListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>> localVarResponse = await PermissionListeParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PermissionCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<PermissionCore>>> PermissionListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<PermissionCore>>("/permission/liste-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>PermissionCoreResultatPage</returns>
        public PermissionCoreResultatPage PermissionListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage> localVarResponse = PermissionListeParPagePageNumeroPageTailleGetWithHttpInfo(pageNumero, pageTaille);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of PermissionCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage> PermissionListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<PermissionCoreResultatPage>("/permission/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PermissionCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<PermissionCoreResultatPage> PermissionListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage> localVarResponse = await PermissionListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(pageNumero, pageTaille, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PermissionCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCoreResultatPage>> PermissionListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PermissionCoreResultatPage>("/permission/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool PermissionModifierPut(PermissionCore permissionCore = default(PermissionCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = PermissionModifierPutWithHttpInfo(permissionCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> PermissionModifierPutWithHttpInfo(PermissionCore permissionCore = default(PermissionCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = permissionCore;


            // make the HTTP request
            var localVarResponse = this.Client.Put<bool>("/permission/modifier", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> PermissionModifierPutAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await PermissionModifierPutWithHttpInfoAsync(permissionCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> PermissionModifierPutWithHttpInfoAsync(PermissionCore permissionCore = default(PermissionCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = permissionCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<bool>("/permission/modifier", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>PermissionCore</returns>
        public PermissionCore PermissionObtenirIdIdGet(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCore> localVarResponse = PermissionObtenirIdIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of PermissionCore</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCore> PermissionObtenirIdIdGetWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling PermissionApi->PermissionObtenirIdIdGet");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<PermissionCore>("/permission/obtenir/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PermissionCore</returns>
        public async System.Threading.Tasks.Task<PermissionCore> PermissionObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCore> localVarResponse = await PermissionObtenirIdIdGetWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PermissionCore)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<PermissionCore>> PermissionObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling PermissionApi->PermissionObtenirIdIdGet");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PermissionCore>("/permission/obtenir/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        public bool PermissionSupprimerIdIdDelete(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = PermissionSupprimerIdIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> PermissionSupprimerIdIdDeleteWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling PermissionApi->PermissionSupprimerIdIdDelete");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<bool>("/permission/supprimer/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> PermissionSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await PermissionSupprimerIdIdDeleteWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> PermissionSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling PermissionApi->PermissionSupprimerIdIdDelete");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<bool>("/permission/supprimer/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        public bool PermissionSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = PermissionSupprimerParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> PermissionSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/permission/supprimer-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> PermissionSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await PermissionSupprimerParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> PermissionSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/permission/supprimer-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PermissionSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
