/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProjetUtilisateurApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>bool</returns>
        bool ProjetutilisateurAjouterPost(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ProjetutilisateurAjouterPostWithHttpInfo(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ProjetUtilisateurCore&gt;</returns>
        List<ProjetUtilisateurCore> ProjetutilisateurListeGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ProjetUtilisateurCore&gt;</returns>
        ApiResponse<List<ProjetUtilisateurCore>> ProjetutilisateurListeGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ProjetUtilisateurCoreResultatPage</returns>
        ProjetUtilisateurCoreResultatPage ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of ProjetUtilisateurCoreResultatPage</returns>
        ApiResponse<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;ProjetUtilisateurCore&gt;</returns>
        List<ProjetUtilisateurCore> ProjetutilisateurListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;ProjetUtilisateurCore&gt;</returns>
        ApiResponse<List<ProjetUtilisateurCore>> ProjetutilisateurListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ProjetUtilisateurCoreResultatPage</returns>
        ProjetUtilisateurCoreResultatPage ProjetutilisateurListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of ProjetUtilisateurCoreResultatPage</returns>
        ApiResponse<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>bool</returns>
        bool ProjetutilisateurModifierPut(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ProjetutilisateurModifierPutWithHttpInfo(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ProjetUtilisateurCore</returns>
        ProjetUtilisateurCore ProjetutilisateurObtenirIdIdGet(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of ProjetUtilisateurCore</returns>
        ApiResponse<ProjetUtilisateurCore> ProjetutilisateurObtenirIdIdGetWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        bool ProjetutilisateurSupprimerIdIdDelete(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ProjetutilisateurSupprimerIdIdDeleteWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        bool ProjetutilisateurSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ProjetutilisateurSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProjetUtilisateurApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ProjetutilisateurAjouterPostAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ProjetutilisateurAjouterPostWithHttpInfoAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ProjetUtilisateurCore&gt;</returns>
        System.Threading.Tasks.Task<List<ProjetUtilisateurCore>> ProjetutilisateurListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ProjetUtilisateurCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ProjetUtilisateurCore>>> ProjetutilisateurListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjetUtilisateurCoreResultatPage</returns>
        System.Threading.Tasks.Task<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjetUtilisateurCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProjetUtilisateurCoreResultatPage>> ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ProjetUtilisateurCore&gt;</returns>
        System.Threading.Tasks.Task<List<ProjetUtilisateurCore>> ProjetutilisateurListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ProjetUtilisateurCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ProjetUtilisateurCore>>> ProjetutilisateurListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjetUtilisateurCoreResultatPage</returns>
        System.Threading.Tasks.Task<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjetUtilisateurCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProjetUtilisateurCoreResultatPage>> ProjetutilisateurListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ProjetutilisateurModifierPutAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ProjetutilisateurModifierPutWithHttpInfoAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjetUtilisateurCore</returns>
        System.Threading.Tasks.Task<ProjetUtilisateurCore> ProjetutilisateurObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjetUtilisateurCore)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProjetUtilisateurCore>> ProjetutilisateurObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ProjetutilisateurSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ProjetutilisateurSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ProjetutilisateurSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ProjetutilisateurSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProjetUtilisateurApi : IProjetUtilisateurApiSync, IProjetUtilisateurApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProjetUtilisateurApi : IProjetUtilisateurApi
    {
        private Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjetUtilisateurApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProjetUtilisateurApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjetUtilisateurApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProjetUtilisateurApi(String basePath)
        {
            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                new Gestprojet.Core.ApiParamSociete.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjetUtilisateurApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProjetUtilisateurApi(Gestprojet.Core.ApiParamSociete.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjetUtilisateurApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ProjetUtilisateurApi(Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient client, Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient asyncClient, Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool ProjetutilisateurAjouterPost(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ProjetutilisateurAjouterPostWithHttpInfo(projetUtilisateurCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ProjetutilisateurAjouterPostWithHttpInfo(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = projetUtilisateurCore;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/projetutilisateur/ajouter", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ProjetutilisateurAjouterPostAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ProjetutilisateurAjouterPostWithHttpInfoAsync(projetUtilisateurCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ProjetutilisateurAjouterPostWithHttpInfoAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = projetUtilisateurCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/projetutilisateur/ajouter", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ProjetUtilisateurCore&gt;</returns>
        public List<ProjetUtilisateurCore> ProjetutilisateurListeGet()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>> localVarResponse = ProjetutilisateurListeGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ProjetUtilisateurCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>> ProjetutilisateurListeGetWithHttpInfo()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ProjetUtilisateurCore>>("/projetutilisateur/liste", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ProjetUtilisateurCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<ProjetUtilisateurCore>> ProjetutilisateurListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>> localVarResponse = await ProjetutilisateurListeGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ProjetUtilisateurCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>>> ProjetutilisateurListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ProjetUtilisateurCore>>("/projetutilisateur/liste", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ProjetUtilisateurCoreResultatPage</returns>
        public ProjetUtilisateurCoreResultatPage ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage> localVarResponse = ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(pageNumero, pageTaille, critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of ProjetUtilisateurCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ProjetUtilisateurCoreResultatPage>("/projetutilisateur/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjetUtilisateurCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage> localVarResponse = await ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(pageNumero, pageTaille, critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjetUtilisateurCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage>> ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ProjetUtilisateurCoreResultatPage>("/projetutilisateur/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;ProjetUtilisateurCore&gt;</returns>
        public List<ProjetUtilisateurCore> ProjetutilisateurListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>> localVarResponse = ProjetutilisateurListeParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;ProjetUtilisateurCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>> ProjetutilisateurListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<ProjetUtilisateurCore>>("/projetutilisateur/liste-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ProjetUtilisateurCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<ProjetUtilisateurCore>> ProjetutilisateurListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>> localVarResponse = await ProjetutilisateurListeParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ProjetUtilisateurCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<ProjetUtilisateurCore>>> ProjetutilisateurListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<ProjetUtilisateurCore>>("/projetutilisateur/liste-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ProjetUtilisateurCoreResultatPage</returns>
        public ProjetUtilisateurCoreResultatPage ProjetutilisateurListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage> localVarResponse = ProjetutilisateurListeParPagePageNumeroPageTailleGetWithHttpInfo(pageNumero, pageTaille);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of ProjetUtilisateurCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<ProjetUtilisateurCoreResultatPage>("/projetutilisateur/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjetUtilisateurCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<ProjetUtilisateurCoreResultatPage> ProjetutilisateurListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage> localVarResponse = await ProjetutilisateurListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(pageNumero, pageTaille, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjetUtilisateurCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCoreResultatPage>> ProjetutilisateurListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ProjetUtilisateurCoreResultatPage>("/projetutilisateur/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool ProjetutilisateurModifierPut(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ProjetutilisateurModifierPutWithHttpInfo(projetUtilisateurCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ProjetutilisateurModifierPutWithHttpInfo(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = projetUtilisateurCore;


            // make the HTTP request
            var localVarResponse = this.Client.Put<bool>("/projetutilisateur/modifier", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ProjetutilisateurModifierPutAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ProjetutilisateurModifierPutWithHttpInfoAsync(projetUtilisateurCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projetUtilisateurCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ProjetutilisateurModifierPutWithHttpInfoAsync(ProjetUtilisateurCore projetUtilisateurCore = default(ProjetUtilisateurCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = projetUtilisateurCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<bool>("/projetutilisateur/modifier", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ProjetUtilisateurCore</returns>
        public ProjetUtilisateurCore ProjetutilisateurObtenirIdIdGet(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCore> localVarResponse = ProjetutilisateurObtenirIdIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of ProjetUtilisateurCore</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCore> ProjetutilisateurObtenirIdIdGetWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ProjetUtilisateurApi->ProjetutilisateurObtenirIdIdGet");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<ProjetUtilisateurCore>("/projetutilisateur/obtenir/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjetUtilisateurCore</returns>
        public async System.Threading.Tasks.Task<ProjetUtilisateurCore> ProjetutilisateurObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCore> localVarResponse = await ProjetutilisateurObtenirIdIdGetWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjetUtilisateurCore)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<ProjetUtilisateurCore>> ProjetutilisateurObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ProjetUtilisateurApi->ProjetutilisateurObtenirIdIdGet");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ProjetUtilisateurCore>("/projetutilisateur/obtenir/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        public bool ProjetutilisateurSupprimerIdIdDelete(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ProjetutilisateurSupprimerIdIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ProjetutilisateurSupprimerIdIdDeleteWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ProjetUtilisateurApi->ProjetutilisateurSupprimerIdIdDelete");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<bool>("/projetutilisateur/supprimer/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ProjetutilisateurSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ProjetutilisateurSupprimerIdIdDeleteWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ProjetutilisateurSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ProjetUtilisateurApi->ProjetutilisateurSupprimerIdIdDelete");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<bool>("/projetutilisateur/supprimer/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        public bool ProjetutilisateurSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ProjetutilisateurSupprimerParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ProjetutilisateurSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/projetutilisateur/supprimer-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ProjetutilisateurSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ProjetutilisateurSupprimerParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ProjetutilisateurSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/projetutilisateur/supprimer-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProjetutilisateurSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
