/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Gestprojet.Core.ApiParamSociete.Client.Client;
using Gestprojet.Core.ApiParamSociete.Client.Model;

namespace Gestprojet.Core.ApiParamSociete.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRoleApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>bool</returns>
        bool ApiRolesAjouterPost(RoleCore roleCore = default(RoleCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiRolesAjouterPostWithHttpInfo(RoleCore roleCore = default(RoleCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;RoleCore&gt;</returns>
        List<RoleCore> ApiRolesGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;RoleCore&gt;</returns>
        ApiResponse<List<RoleCore>> ApiRolesGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;RoleCore&gt;</returns>
        List<RoleCore> ApiRolesListeGet();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;RoleCore&gt;</returns>
        ApiResponse<List<RoleCore>> ApiRolesListeGetWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>RoleCoreResultatPage</returns>
        RoleCoreResultatPage ApiRolesListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of RoleCoreResultatPage</returns>
        ApiResponse<RoleCoreResultatPage> ApiRolesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;RoleCore&gt;</returns>
        List<RoleCore> ApiRolesListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;RoleCore&gt;</returns>
        ApiResponse<List<RoleCore>> ApiRolesListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>RoleCoreResultatPage</returns>
        RoleCoreResultatPage ApiRolesListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of RoleCoreResultatPage</returns>
        ApiResponse<RoleCoreResultatPage> ApiRolesListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>bool</returns>
        bool ApiRolesModifierPut(RoleCore roleCore = default(RoleCore));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiRolesModifierPutWithHttpInfo(RoleCore roleCore = default(RoleCore));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>RoleCore</returns>
        RoleCore ApiRolesObtenirIdIdGet(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of RoleCore</returns>
        ApiResponse<RoleCore> ApiRolesObtenirIdIdGetWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        bool ApiRolesSupprimerIdIdDelete(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiRolesSupprimerIdIdDeleteWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        bool ApiRolesSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        ApiResponse<bool> ApiRolesSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRoleApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiRolesAjouterPostAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiRolesAjouterPostWithHttpInfoAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;RoleCore&gt;</returns>
        System.Threading.Tasks.Task<List<RoleCore>> ApiRolesGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;RoleCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<RoleCore>>> ApiRolesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;RoleCore&gt;</returns>
        System.Threading.Tasks.Task<List<RoleCore>> ApiRolesListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;RoleCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<RoleCore>>> ApiRolesListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleCoreResultatPage</returns>
        System.Threading.Tasks.Task<RoleCoreResultatPage> ApiRolesListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<RoleCoreResultatPage>> ApiRolesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;RoleCore&gt;</returns>
        System.Threading.Tasks.Task<List<RoleCore>> ApiRolesListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;RoleCore&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<RoleCore>>> ApiRolesListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleCoreResultatPage</returns>
        System.Threading.Tasks.Task<RoleCoreResultatPage> ApiRolesListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleCoreResultatPage)</returns>
        System.Threading.Tasks.Task<ApiResponse<RoleCoreResultatPage>> ApiRolesListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiRolesModifierPutAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiRolesModifierPutWithHttpInfoAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleCore</returns>
        System.Threading.Tasks.Task<RoleCore> ApiRolesObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleCore)</returns>
        System.Threading.Tasks.Task<ApiResponse<RoleCore>> ApiRolesObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiRolesSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiRolesSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        System.Threading.Tasks.Task<bool> ApiRolesSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        System.Threading.Tasks.Task<ApiResponse<bool>> ApiRolesSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRoleApi : IRoleApiSync, IRoleApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RoleApi : IRoleApi
    {
        private Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RoleApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RoleApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RoleApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RoleApi(String basePath)
        {
            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                new Gestprojet.Core.ApiParamSociete.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RoleApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RoleApi(Gestprojet.Core.ApiParamSociete.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.MergeConfigurations(
                Gestprojet.Core.ApiParamSociete.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Gestprojet.Core.ApiParamSociete.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RoleApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RoleApi(Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient client, Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient asyncClient, Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Gestprojet.Core.ApiParamSociete.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Gestprojet.Core.ApiParamSociete.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool ApiRolesAjouterPost(RoleCore roleCore = default(RoleCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiRolesAjouterPostWithHttpInfo(roleCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiRolesAjouterPostWithHttpInfo(RoleCore roleCore = default(RoleCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = roleCore;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/api/roles/ajouter", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiRolesAjouterPostAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiRolesAjouterPostWithHttpInfoAsync(roleCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiRolesAjouterPostWithHttpInfoAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = roleCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/api/roles/ajouter", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesAjouterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;RoleCore&gt;</returns>
        public List<RoleCore> ApiRolesGet()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> localVarResponse = ApiRolesGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;RoleCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> ApiRolesGetWithHttpInfo()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<RoleCore>>("/api/roles", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;RoleCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<RoleCore>> ApiRolesGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> localVarResponse = await ApiRolesGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;RoleCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>>> ApiRolesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<RoleCore>>("/api/roles", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;RoleCore&gt;</returns>
        public List<RoleCore> ApiRolesListeGet()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> localVarResponse = ApiRolesListeGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;RoleCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> ApiRolesListeGetWithHttpInfo()
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<RoleCore>>("/api/roles/liste", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;RoleCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<RoleCore>> ApiRolesListeGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> localVarResponse = await ApiRolesListeGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;RoleCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>>> ApiRolesListeGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<RoleCore>>("/api/roles/liste", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>RoleCoreResultatPage</returns>
        public RoleCoreResultatPage ApiRolesListeParConditionParPagePageNumeroPageTaillePost(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage> localVarResponse = ApiRolesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(pageNumero, pageTaille, critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of RoleCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage> ApiRolesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfo(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<RoleCoreResultatPage>("/api/roles/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<RoleCoreResultatPage> ApiRolesListeParConditionParPagePageNumeroPageTaillePostAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage> localVarResponse = await ApiRolesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(pageNumero, pageTaille, critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage>> ApiRolesListeParConditionParPagePageNumeroPageTaillePostWithHttpInfoAsync(int pageNumero, int pageTaille, CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter
            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<RoleCoreResultatPage>("/api/roles/liste-par-condition-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeParConditionParPagePageNumeroPageTaillePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>List&lt;RoleCore&gt;</returns>
        public List<RoleCore> ApiRolesListeParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> localVarResponse = ApiRolesListeParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of List&lt;RoleCore&gt;</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> ApiRolesListeParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<RoleCore>>("/api/roles/liste-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;RoleCore&gt;</returns>
        public async System.Threading.Tasks.Task<List<RoleCore>> ApiRolesListeParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>> localVarResponse = await ApiRolesListeParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;RoleCore&gt;)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<List<RoleCore>>> ApiRolesListeParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<List<RoleCore>>("/api/roles/liste-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>RoleCoreResultatPage</returns>
        public RoleCoreResultatPage ApiRolesListeParPagePageNumeroPageTailleGet(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage> localVarResponse = ApiRolesListeParPagePageNumeroPageTailleGetWithHttpInfo(pageNumero, pageTaille);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <returns>ApiResponse of RoleCoreResultatPage</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage> ApiRolesListeParPagePageNumeroPageTailleGetWithHttpInfo(int pageNumero, int pageTaille)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<RoleCoreResultatPage>("/api/roles/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleCoreResultatPage</returns>
        public async System.Threading.Tasks.Task<RoleCoreResultatPage> ApiRolesListeParPagePageNumeroPageTailleGetAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage> localVarResponse = await ApiRolesListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(pageNumero, pageTaille, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumero"></param>
        /// <param name="pageTaille"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleCoreResultatPage)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCoreResultatPage>> ApiRolesListeParPagePageNumeroPageTailleGetWithHttpInfoAsync(int pageNumero, int pageTaille, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("pageNumero", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageNumero)); // path parameter
            localVarRequestOptions.PathParameters.Add("pageTaille", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(pageTaille)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<RoleCoreResultatPage>("/api/roles/liste-par-page/{pageNumero}/{pageTaille}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesListeParPagePageNumeroPageTailleGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>bool</returns>
        public bool ApiRolesModifierPut(RoleCore roleCore = default(RoleCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiRolesModifierPutWithHttpInfo(roleCore);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiRolesModifierPutWithHttpInfo(RoleCore roleCore = default(RoleCore))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = roleCore;


            // make the HTTP request
            var localVarResponse = this.Client.Put<bool>("/api/roles/modifier", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiRolesModifierPutAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiRolesModifierPutWithHttpInfoAsync(roleCore, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roleCore"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiRolesModifierPutWithHttpInfoAsync(RoleCore roleCore = default(RoleCore), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = roleCore;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<bool>("/api/roles/modifier", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesModifierPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>RoleCore</returns>
        public RoleCore ApiRolesObtenirIdIdGet(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCore> localVarResponse = ApiRolesObtenirIdIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of RoleCore</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCore> ApiRolesObtenirIdIdGetWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling RoleApi->ApiRolesObtenirIdIdGet");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<RoleCore>("/api/roles/obtenir/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RoleCore</returns>
        public async System.Threading.Tasks.Task<RoleCore> ApiRolesObtenirIdIdGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCore> localVarResponse = await ApiRolesObtenirIdIdGetWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RoleCore)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<RoleCore>> ApiRolesObtenirIdIdGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling RoleApi->ApiRolesObtenirIdIdGet");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<RoleCore>("/api/roles/obtenir/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesObtenirIdIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        public bool ApiRolesSupprimerIdIdDelete(string id)
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiRolesSupprimerIdIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiRolesSupprimerIdIdDeleteWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling RoleApi->ApiRolesSupprimerIdIdDelete");

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<bool>("/api/roles/supprimer/id/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiRolesSupprimerIdIdDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiRolesSupprimerIdIdDeleteWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiRolesSupprimerIdIdDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Gestprojet.Core.ApiParamSociete.Client.Client.ApiException(400, "Missing required parameter 'id' when calling RoleApi->ApiRolesSupprimerIdIdDelete");


            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<bool>("/api/roles/supprimer/id/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesSupprimerIdIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>bool</returns>
        public bool ApiRolesSupprimerParConditionPost(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = ApiRolesSupprimerParConditionPostWithHttpInfo(critereRecherche);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <returns>ApiResponse of bool</returns>
        public Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> ApiRolesSupprimerParConditionPostWithHttpInfo(CritereRecherche critereRecherche = default(CritereRecherche))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request
            var localVarResponse = this.Client.Post<bool>("/api/roles/supprimer-par-condition", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of bool</returns>
        public async System.Threading.Tasks.Task<bool> ApiRolesSupprimerParConditionPostAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool> localVarResponse = await ApiRolesSupprimerParConditionPostWithHttpInfoAsync(critereRecherche, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Gestprojet.Core.ApiParamSociete.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="critereRecherche"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (bool)</returns>
        public async System.Threading.Tasks.Task<Gestprojet.Core.ApiParamSociete.Client.Client.ApiResponse<bool>> ApiRolesSupprimerParConditionPostWithHttpInfoAsync(CritereRecherche critereRecherche = default(CritereRecherche), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions localVarRequestOptions = new Gestprojet.Core.ApiParamSociete.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Gestprojet.Core.ApiParamSociete.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = critereRecherche;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<bool>("/api/roles/supprimer-par-condition", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiRolesSupprimerParConditionPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
