/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Gestprojet.Core.ApiParamSociete.Client.Client.OpenAPIDateConverter;

namespace Gestprojet.Core.ApiParamSociete.Client.Model
{
    /// <summary>
    /// AttachementCore
    /// </summary>
    [DataContract(Name = "AttachementCore")]
    public partial class AttachementCore : IEquatable<AttachementCore>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttachementCore" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="tacheId">tacheId.</param>
        /// <param name="projetId">projetId.</param>
        /// <param name="cheminFichier">cheminFichier.</param>
        /// <param name="typeFichier">typeFichier.</param>
        /// <param name="actif">actif.</param>
        public AttachementCore(string id = default(string), string tacheId = default(string), string projetId = default(string), string cheminFichier = default(string), string typeFichier = default(string), bool? actif = default(bool?))
        {
            this.Id = id;
            this.TacheId = tacheId;
            this.ProjetId = projetId;
            this.CheminFichier = cheminFichier;
            this.TypeFichier = typeFichier;
            this.Actif = actif;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TacheId
        /// </summary>
        [DataMember(Name = "tacheId", EmitDefaultValue = true)]
        public string TacheId { get; set; }

        /// <summary>
        /// Gets or Sets ProjetId
        /// </summary>
        [DataMember(Name = "projetId", EmitDefaultValue = true)]
        public string ProjetId { get; set; }

        /// <summary>
        /// Gets or Sets CheminFichier
        /// </summary>
        [DataMember(Name = "cheminFichier", EmitDefaultValue = true)]
        public string CheminFichier { get; set; }

        /// <summary>
        /// Gets or Sets TypeFichier
        /// </summary>
        [DataMember(Name = "typeFichier", EmitDefaultValue = true)]
        public string TypeFichier { get; set; }

        /// <summary>
        /// Gets or Sets Actif
        /// </summary>
        [DataMember(Name = "actif", EmitDefaultValue = true)]
        public bool? Actif { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AttachementCore {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TacheId: ").Append(TacheId).Append("\n");
            sb.Append("  ProjetId: ").Append(ProjetId).Append("\n");
            sb.Append("  CheminFichier: ").Append(CheminFichier).Append("\n");
            sb.Append("  TypeFichier: ").Append(TypeFichier).Append("\n");
            sb.Append("  Actif: ").Append(Actif).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AttachementCore);
        }

        /// <summary>
        /// Returns true if AttachementCore instances are equal
        /// </summary>
        /// <param name="input">Instance of AttachementCore to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AttachementCore input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.TacheId == input.TacheId ||
                    (this.TacheId != null &&
                    this.TacheId.Equals(input.TacheId))
                ) && 
                (
                    this.ProjetId == input.ProjetId ||
                    (this.ProjetId != null &&
                    this.ProjetId.Equals(input.ProjetId))
                ) && 
                (
                    this.CheminFichier == input.CheminFichier ||
                    (this.CheminFichier != null &&
                    this.CheminFichier.Equals(input.CheminFichier))
                ) && 
                (
                    this.TypeFichier == input.TypeFichier ||
                    (this.TypeFichier != null &&
                    this.TypeFichier.Equals(input.TypeFichier))
                ) && 
                (
                    this.Actif == input.Actif ||
                    (this.Actif != null &&
                    this.Actif.Equals(input.Actif))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.TacheId != null)
                    hashCode = hashCode * 59 + this.TacheId.GetHashCode();
                if (this.ProjetId != null)
                    hashCode = hashCode * 59 + this.ProjetId.GetHashCode();
                if (this.CheminFichier != null)
                    hashCode = hashCode * 59 + this.CheminFichier.GetHashCode();
                if (this.TypeFichier != null)
                    hashCode = hashCode * 59 + this.TypeFichier.GetHashCode();
                if (this.Actif != null)
                    hashCode = hashCode * 59 + this.Actif.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CheminFichier (string) maxLength
            if(this.CheminFichier != null && this.CheminFichier.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CheminFichier, length must be less than 255.", new [] { "CheminFichier" });
            }

            // TypeFichier (string) maxLength
            if(this.TypeFichier != null && this.TypeFichier.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TypeFichier, length must be less than 50.", new [] { "TypeFichier" });
            }

            yield break;
        }
    }

}
