/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Gestprojet.Core.ApiParamSociete.Client.Client.OpenAPIDateConverter;

namespace Gestprojet.Core.ApiParamSociete.Client.Model
{
    /// <summary>
    /// ProjetUtilisateurCore
    /// </summary>
    [DataContract(Name = "ProjetUtilisateurCore")]
    public partial class ProjetUtilisateurCore : IEquatable<ProjetUtilisateurCore>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjetUtilisateurCore" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="projetId">projetId.</param>
        /// <param name="utilisateurId">utilisateurId.</param>
        /// <param name="actif">actif.</param>
        public ProjetUtilisateurCore(string id = default(string), string projetId = default(string), string utilisateurId = default(string), bool? actif = default(bool?))
        {
            this.Id = id;
            this.ProjetId = projetId;
            this.UtilisateurId = utilisateurId;
            this.Actif = actif;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ProjetId
        /// </summary>
        [DataMember(Name = "projetId", EmitDefaultValue = true)]
        public string ProjetId { get; set; }

        /// <summary>
        /// Gets or Sets UtilisateurId
        /// </summary>
        [DataMember(Name = "utilisateurId", EmitDefaultValue = true)]
        public string UtilisateurId { get; set; }

        /// <summary>
        /// Gets or Sets Actif
        /// </summary>
        [DataMember(Name = "actif", EmitDefaultValue = true)]
        public bool? Actif { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjetUtilisateurCore {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProjetId: ").Append(ProjetId).Append("\n");
            sb.Append("  UtilisateurId: ").Append(UtilisateurId).Append("\n");
            sb.Append("  Actif: ").Append(Actif).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProjetUtilisateurCore);
        }

        /// <summary>
        /// Returns true if ProjetUtilisateurCore instances are equal
        /// </summary>
        /// <param name="input">Instance of ProjetUtilisateurCore to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjetUtilisateurCore input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ProjetId == input.ProjetId ||
                    (this.ProjetId != null &&
                    this.ProjetId.Equals(input.ProjetId))
                ) && 
                (
                    this.UtilisateurId == input.UtilisateurId ||
                    (this.UtilisateurId != null &&
                    this.UtilisateurId.Equals(input.UtilisateurId))
                ) && 
                (
                    this.Actif == input.Actif ||
                    (this.Actif != null &&
                    this.Actif.Equals(input.Actif))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ProjetId != null)
                    hashCode = hashCode * 59 + this.ProjetId.GetHashCode();
                if (this.UtilisateurId != null)
                    hashCode = hashCode * 59 + this.UtilisateurId.GetHashCode();
                if (this.Actif != null)
                    hashCode = hashCode * 59 + this.Actif.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
