/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Gestprojet.Core.ApiParamSociete.Client.Client.OpenAPIDateConverter;

namespace Gestprojet.Core.ApiParamSociete.Client.Model
{
    /// <summary>
    /// SocieteCore
    /// </summary>
    [DataContract(Name = "SocieteCore")]
    public partial class SocieteCore : IEquatable<SocieteCore>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SocieteCore" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="nom">nom.</param>
        /// <param name="adresse">adresse.</param>
        /// <param name="planAbonnement">planAbonnement.</param>
        /// <param name="actif">actif.</param>
        public SocieteCore(string id = default(string), string nom = default(string), string adresse = default(string), string planAbonnement = default(string), bool? actif = default(bool?), string telephoneContact = default(string), string email = default(string), string codePostale = default(string), string ville = default(string), string pays = default(string), string personneContact = default(string), string fax = default(string), string siteWeb = default(string))
        {
            this.Id = id;
            this.Nom = nom;
            this.Adresse = adresse;
            this.PlanAbonnement = planAbonnement;
            this.Actif = actif;
            this.TelephoneContact = telephoneContact;
            this.Email = email;
            this.CodePostale = codePostale;
            this.Ville = ville;
            this.Pays = pays;
            this.PersonneContact = personneContact;
            this.Fax = fax;
            this.SiteWeb = siteWeb;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Nom
        /// </summary>
        [DataMember(Name = "nom", EmitDefaultValue = true)]
        public string Nom { get; set; }

        /// <summary>
        /// Gets or Sets Adresse
        /// </summary>
        [DataMember(Name = "adresse", EmitDefaultValue = true)]
        public string Adresse { get; set; }

        /// <summary>
        /// Gets or Sets PlanAbonnement
        /// </summary>
        [DataMember(Name = "planAbonnement", EmitDefaultValue = true)]
        public string PlanAbonnement { get; set; }

        /// <summary>
        /// Gets or Sets Actif
        /// </summary>
        [DataMember(Name = "actif", EmitDefaultValue = true)]
        public bool? Actif { get; set; }

        /// <summary>
        /// Gets or Sets TelephoneContact
        /// </summary>
        [DataMember(Name = "telephoneContact", EmitDefaultValue = true)]
        public string TelephoneContact { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets CodePostale
        /// </summary>
        [DataMember(Name = "codePostale", EmitDefaultValue = true)]
        public string CodePostale { get; set; }

        /// <summary>
        /// Gets or Sets Ville
        /// </summary>
        [DataMember(Name = "ville", EmitDefaultValue = true)]
        public string Ville { get; set; }

        /// <summary>
        /// Gets or Sets Pays
        /// </summary>
        [DataMember(Name = "pays", EmitDefaultValue = true)]
        public string Pays { get; set; }

        /// <summary>
        /// Gets or Sets PersonneContact
        /// </summary>
        [DataMember(Name = "personneContact", EmitDefaultValue = true)]
        public string PersonneContact { get; set; }

        /// <summary>
        /// Gets or Sets Fax
        /// </summary>
        [DataMember(Name = "fax", EmitDefaultValue = true)]
        public string Fax { get; set; }

        /// <summary>
        /// Gets or Sets SiteWeb
        /// </summary>
        [DataMember(Name = "siteWeb", EmitDefaultValue = true)]
        public string SiteWeb { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SocieteCore {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Nom: ").Append(Nom).Append("\n");
            sb.Append("  Adresse: ").Append(Adresse).Append("\n");
            sb.Append("  PlanAbonnement: ").Append(PlanAbonnement).Append("\n");
            sb.Append("  Actif: ").Append(Actif).Append("\n");
            sb.Append("  TelephoneContact: ").Append(TelephoneContact).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Ville: ").Append(Ville).Append("\n");
            sb.Append("  Pays: ").Append(Pays).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SocieteCore);
        }

        /// <summary>
        /// Returns true if SocieteCore instances are equal
        /// </summary>
        /// <param name="input">Instance of SocieteCore to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SocieteCore input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Nom == input.Nom ||
                    (this.Nom != null &&
                    this.Nom.Equals(input.Nom))
                ) && 
                (
                    this.Adresse == input.Adresse ||
                    (this.Adresse != null &&
                    this.Adresse.Equals(input.Adresse))
                ) && 
                (
                    this.PlanAbonnement == input.PlanAbonnement ||
                    (this.PlanAbonnement != null &&
                    this.PlanAbonnement.Equals(input.PlanAbonnement))
                ) && 
                (
                    this.Actif == input.Actif ||
                    (this.Actif != null &&
                    this.Actif.Equals(input.Actif))
                ) &&
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) &&
                (
                    this.TelephoneContact == input.TelephoneContact ||
                    (this.TelephoneContact != null &&
                    this.TelephoneContact.Equals(input.TelephoneContact))
                ) &&
                (
                    this.Ville == input.Ville ||
                    (this.Ville != null &&
                    this.Ville.Equals(input.Ville))
                ) &&
                (
                    this.Pays == input.Pays ||
                    (this.Pays != null &&
                    this.Pays.Equals(input.Pays))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Nom != null)
                    hashCode = hashCode * 59 + this.Nom.GetHashCode();
                if (this.Adresse != null)
                    hashCode = hashCode * 59 + this.Adresse.GetHashCode();
                if (this.PlanAbonnement != null)
                    hashCode = hashCode * 59 + this.PlanAbonnement.GetHashCode();
                if (this.Actif != null)
                    hashCode = hashCode * 59 + this.Actif.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.TelephoneContact != null)
                    hashCode = hashCode * 59 + this.TelephoneContact.GetHashCode();
                if (this.Ville != null)
                    hashCode = hashCode * 59 + this.Ville.GetHashCode();
                if (this.Pays != null)
                    hashCode = hashCode * 59 + this.Pays.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Nom (string) maxLength
            if(this.Nom != null && this.Nom.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nom, length must be less than 100.", new [] { "Nom" });
            }

            // Adresse (string) maxLength
            if(this.Adresse != null && this.Adresse.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Adresse, length must be less than 255.", new [] { "Adresse" });
            }

            // PlanAbonnement (string) maxLength
            if(this.PlanAbonnement != null && this.PlanAbonnement.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PlanAbonnement, length must be less than 100.", new [] { "PlanAbonnement" });
            }

            yield break;
        }
    }

}
