/*
 * Gestprojet.Core.ApiParamSociete.WebApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Gestprojet.Core.ApiParamSociete.Client.Client.OpenAPIDateConverter;

namespace Gestprojet.Core.ApiParamSociete.Client.Model
{
    /// <summary>
    /// UtilisateurCore
    /// </summary>
    [DataContract(Name = "UtilisateurCore")]
    public partial class UtilisateurCore : IEquatable<UtilisateurCore>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UtilisateurCore" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="nom">nom.</param>
        /// <param name="email">email.</param>
        /// <param name="motDePasse">motDePasse.</param>
        /// <param name="cv">cv.</param>
        /// <param name="typeUtilisateurId">typeUtilisateurId.</param>
        /// <param name="societeId">societeId.</param>
        /// <param name="roleId">roleId.</param>
        /// <param name="actif">actif.</param>
        public UtilisateurCore(string id = default(string), string nom = default(string), string email = default(string), string motDePasse = default(string), string cv = default(string), string typeUtilisateurId = default(string), string societeId = default(string), string roleId = default(string), bool? actif = default(bool?), string telephone = default(string))
        {
            this.Id = id;
            this.Nom = nom;
            this.Email = email;
            this.MotDePasse = motDePasse;
            this.Cv = cv;
            this.TypeUtilisateurId = typeUtilisateurId;
            this.SocieteId = societeId;
            this.RoleId = roleId;
            this.Actif = actif;
            this.Telephone = telephone;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Nom
        /// </summary>
        [DataMember(Name = "nom", EmitDefaultValue = true)]
        public string Nom { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets MotDePasse
        /// </summary>
        [DataMember(Name = "motDePasse", EmitDefaultValue = true)]
        public string MotDePasse { get; set; }

        /// <summary>
        /// Gets or Sets Cv
        /// </summary>
        [DataMember(Name = "cv", EmitDefaultValue = true)]
        public string Cv { get; set; }

        /// <summary>
        /// Gets or Sets TypeUtilisateurId
        /// </summary>
        [DataMember(Name = "typeUtilisateurId", EmitDefaultValue = true)]
        public string TypeUtilisateurId { get; set; }

        /// <summary>
        /// Gets or Sets SocieteId
        /// </summary>
        [DataMember(Name = "societeId", EmitDefaultValue = true)]
        public string SocieteId { get; set; }

        /// <summary>
        /// Gets or Sets RoleId
        /// </summary>
        [DataMember(Name = "roleId", EmitDefaultValue = true)]
        public string RoleId { get; set; }

        /// <summary>
        /// Gets or Sets Actif
        /// </summary>
        [DataMember(Name = "actif", EmitDefaultValue = true)]
        public bool? Actif { get; set; }

        /// <summary>
        /// Gets or Sets Telephone
        /// </summary>
        [DataMember(Name = "telephone", EmitDefaultValue = true)]
        public string Telephone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UtilisateurCore {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Nom: ").Append(Nom).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  MotDePasse: ").Append(MotDePasse).Append("\n");
            sb.Append("  Cv: ").Append(Cv).Append("\n");
            sb.Append("  TypeUtilisateurId: ").Append(TypeUtilisateurId).Append("\n");
            sb.Append("  SocieteId: ").Append(SocieteId).Append("\n");
            sb.Append("  RoleId: ").Append(RoleId).Append("\n");
            sb.Append("  Actif: ").Append(Actif).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UtilisateurCore);
        }

        /// <summary>
        /// Returns true if UtilisateurCore instances are equal
        /// </summary>
        /// <param name="input">Instance of UtilisateurCore to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UtilisateurCore input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Nom == input.Nom ||
                    (this.Nom != null &&
                    this.Nom.Equals(input.Nom))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.MotDePasse == input.MotDePasse ||
                    (this.MotDePasse != null &&
                    this.MotDePasse.Equals(input.MotDePasse))
                ) && 
                (
                    this.Cv == input.Cv ||
                    (this.Cv != null &&
                    this.Cv.Equals(input.Cv))
                ) && 
                (
                    this.TypeUtilisateurId == input.TypeUtilisateurId ||
                    (this.TypeUtilisateurId != null &&
                    this.TypeUtilisateurId.Equals(input.TypeUtilisateurId))
                ) && 
                (
                    this.SocieteId == input.SocieteId ||
                    (this.SocieteId != null &&
                    this.SocieteId.Equals(input.SocieteId))
                ) && 
                (
                    this.RoleId == input.RoleId ||
                    (this.RoleId != null &&
                    this.RoleId.Equals(input.RoleId))
                ) && 
                (
                    this.Actif == input.Actif ||
                    (this.Actif != null &&
                    this.Actif.Equals(input.Actif))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Nom != null)
                    hashCode = hashCode * 59 + this.Nom.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.MotDePasse != null)
                    hashCode = hashCode * 59 + this.MotDePasse.GetHashCode();
                if (this.Cv != null)
                    hashCode = hashCode * 59 + this.Cv.GetHashCode();
                if (this.TypeUtilisateurId != null)
                    hashCode = hashCode * 59 + this.TypeUtilisateurId.GetHashCode();
                if (this.SocieteId != null)
                    hashCode = hashCode * 59 + this.SocieteId.GetHashCode();
                if (this.RoleId != null)
                    hashCode = hashCode * 59 + this.RoleId.GetHashCode();
                if (this.Actif != null)
                    hashCode = hashCode * 59 + this.Actif.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Nom (string) maxLength
            if(this.Nom != null && this.Nom.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nom, length must be less than 100.", new [] { "Nom" });
            }

            // Email (string) maxLength
            if(this.Email != null && this.Email.Length > 150)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Email, length must be less than 150.", new [] { "Email" });
            }

            // MotDePasse (string) maxLength
            if(this.MotDePasse != null && this.MotDePasse.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MotDePasse, length must be less than 255.", new [] { "MotDePasse" });
            }

            // Cv (string) maxLength
            if(this.Cv != null && this.Cv.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Cv, length must be less than 255.", new [] { "Cv" });
            }

            yield break;
        }
    }

}
